name = "Hexmc Testing"
author = "Tabzlock"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7160f8da2c8de50499cc2791c252c48428858d399f2db1f825c2de9737ff0ff5"

[versions]
minecraft = "1.18.2"
quilt = "0.17.5-beta.1"
