name = "Hexmc Testing"
author = "Tabzlock"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c87e5b42c50f5b2808ddc2342b5e3f3f4ff746683873049f2c1b3e273e78360"

[versions]
minecraft = "1.18.2"
quilt = "0.17.5-beta.1"
